nodeLinker: node-modules

npmScopes:
  flash-ship:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GH_TOKEN:-${YARN_NPM_AUTH_TOKEN:-${NODE_AUTH_TOKEN:-${GITHUB_TOKEN:-}}}}"
