import { router } from "@flash-ship/ecom-trpc/server/trpc";
import {
  clearCacheNamespace,
  deleteRequestLog,
  executeDbCommand,
  executeLogCommand,
  executeProcessAction,
  getAuthorStats,
  getCacheStats,
  getCategoryStats,
  getDashboardStats,
  getDatabaseStats,
  getEngagementOverview,
  getLogLevel,
  getPopularContent,
  getProcessStatus,
  getPublishingTrends,
  getQueueDashboardUrl,
  getRedisStats,
  getRequestStats,
  getStatusBreakdown,
  getSystemInfo,
  getWorkflowDescription,
  getWorkflowTransitions,
  listLogFiles,
  listRequestLogs,
  pingServices,
  purgeRequestLogs,
  queryRedis,
  updateLogLevel,
} from "./procedures/system.handler";

export const systemRouter = router({
  requestLogs: listRequestLogs,
  requestStats: getRequestStats,
  purgeRequestLogs: purgeRequestLogs,
  deleteRequestLog: deleteRequestLog,
  systemInfo: getSystemInfo,
  dashboardStats: getDashboardStats,
  publishingTrends: getPublishingTrends,
  popularContent: getPopularContent,
  statusBreakdown: getStatusBreakdown,
  authorStats: getAuthorStats,
  categoryStats: getCategoryStats,
  engagementOverview: getEngagementOverview,
  workflowTransitions: getWorkflowTransitions,
  workflowDescription: getWorkflowDescription,
  cacheStats: getCacheStats,
  clearCache: clearCacheNamespace,
  getQueueDashboardUrl,
  listLogFiles,
  getProcessStatus,
  executeProcessAction,
  pingServices,
  queryRedis,
  executeDbCommand,
  executeLogCommand,
  getLogLevel,
  updateLogLevel,
  getDatabaseStats,
  getRedisStats,
});
