import { router } from "@flash-ship/ecom-trpc/server/trpc";
import {
  addToBlacklist,
  addToBlacklistBulk,
  createScheduled,
  deleteNotification,
  deleteScheduled,
  getPreferences,
  listBlacklist,
  listNotifications,
  listScheduled,
  listTemplates,
  markAllRead,
  markRead,
  previewTemplate,
  registerToken,
  removeFromBlacklist,
  removeFromBlacklistBulk,
  resetTemplate,
  sendTestTemplate,
  syncCacheBulk,
  testDispatch,
  unreadCount,
  unregisterToken,
  updateBlacklistReason,
  updatePreference,
  updateTemplate,
} from "./procedures/notifications.handler";

export const notificationsRouter = router({
  list: listNotifications,
  unreadCount,
  markRead,
  markAllRead,
  delete: deleteNotification,
  registerToken,
  unregisterToken,
  getPreferences,
  updatePreference,
  listTemplates,
  updateTemplate,
  sendTestTemplate,
  resetTemplate,
  listScheduled,
  createScheduled,
  deleteScheduled,
  previewTemplate,
  testDispatch,
  blacklist: router({
    list: listBlacklist,
    add: addToBlacklist,
    addBulk: addToBlacklistBulk,
    remove: removeFromBlacklist,
    removeBulk: removeFromBlacklistBulk,
    updateReason: updateBlacklistReason,
    syncCache: syncCacheBulk,
  }),
});
