name: CI Quality Gate

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ecom-web

      - name: Checkout ecom-shared-packages
        uses: actions/checkout@v4
        with:
          repository: FLASH-SHIP/ecom-shared-packages
          path: ecom-shared-packages

      - name: Checkout ecom-api
        uses: actions/checkout@v4
        with:
          repository: FLASH-SHIP/ecom-api
          path: ecom-api

      - name: Enable Corepack
        run: corepack enable
        working-directory: ecom-web

      - name: Setup Node.js & Enable Cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: ecom-web/yarn.lock

      - name: Install Dependencies
        run: yarn install
        working-directory: ecom-web

      - name: Run Type Check
        run: yarn type-check
        working-directory: ecom-web

      - name: Run Production Build
        run: yarn build
        working-directory: ecom-web
        env:
          NEXT_PUBLIC_APP_URL: "http://localhost:3000"
